name: nfe

on:
  push:
    branches: [ main ]
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review]

env:
  CARGO_TERM_COLOR: always

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable     
      - run: cargo test --release --all-features --manifest-path nfe/Cargo.toml
